[package]
name = "sound-mixer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
app-identity.workspace = true
libspa.workspace = true
pipewire.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
