[package]
name = "kavverna-shell"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cxx.workspace = true
cxx-qt.workspace = true
cxx-qt-lib = { workspace = true, features = ["qt_full"] }
ksni.workspace = true
clipboard-history.workspace = true
feature-catalog.workspace = true
directories.workspace = true
kde-bridge.workspace = true
keep-awake.workspace = true
notify-rust.workspace = true
preferences.workspace = true
sound-mixer.workspace = true
strum.workspace = true
system-monitor.workspace = true
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "time"] }
tracing.workspace = true
tracing-subscriber.workspace = true
zbus.workspace = true

[build-dependencies]
cxx-qt-build.workspace = true

[dev-dependencies]
tempfile.workspace = true
