[package]
name = "kde-bridge"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
futures-util.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros"] }
tracing.workspace = true
zbus.workspace = true
